### PR TITLE
Added a section about our specific Swiftlint fork

### PR DESCRIPTION
**Pull request by Haud**
Based off of @prolificphotis feedback, this PR adds a section at the top that links to our fork of `Swiftlint` with additional custom rules / auto corrections specific to our style guide.

### CODE REVIEW

**Comment by ThibaultKlein** [comment]
@Haud who is responsible for maintaining this fork? do you think we should make a PR to the public repo?

**Comment by Haud** [comment]
@ThibaultKlein me / our team would be responsible. 

I thought about making a PR back, but I don't think we should since their repo is specifically oriented towards the GitHub style guide, and I don't think it would make sense to include rules or other style items that are not included in the GitHub style guide in their own Swiftlint fork.

**Comment by ThibaultKlein** [comment]
:+1:

**Comment by paulmiard** [comment]
:+1:

**Pull request merged**
