### PR TITLE
Enums cases in alphabetical order

### PR DESCRIPTION
**Pull request by jstnheo**
Enum cases should be in alphabetical order

### CODE REVIEW

**Comment by maxmamis** [comment]
Disagree. There are many cases where enum cases have a natural order they should come in. To use a contrived example that ignores any numbers greater than 20:

```
enum OrdinalNumber {
    case First
    case Second
    case Third
    case Nth (number: Int)

    func numeralString () -> String {
        switch self {
        case .First:
            return "1st"
        case .Second:
            return "2nd"
        case .Third:
            return "3rd"
        case .Nth(let number):
            return "\(number)th"
        }
    }
}
```

**Comment by Haud** [comment]
Inclined to agree with @maxmamis . Can you describe the rationale behind why you think this should be the case for all enums?

**Comment by ThibaultKlein** [comment]
+1 with @maxmamis, another example would be

```
enum Response {
 case Success
 case Error
}
```

**Comment by jstnheo** [comment]
Good call @maxmamis  and @ThibaultKlein , i guess it doesnt make sense for **all** enums

**Pull request closed without merging**
