### PR TITLE
Added definition for bracket syntax

### PR DESCRIPTION
**Pull request by Haud**
@ThibaultKlein @paulmiard

### CODE REVIEW

**Comment by ThibaultKlein** [comment]
It's not related but did we talk about the spacing between class brackets?

```
class {
<SPACE>
let a = "a"

func doSomething() {
}
<SPACE>
}
```

I feel that's something Apple is doing but I might be wrong, and I like having these spaces to let the class breathe a little bit ;)

**Comment by ThibaultKlein** [comment]
Otherwise :+1:

**Comment by paulmiard** [comment]
Thibault I added your comment/question to the Google doc

**Comment by paulmiard** [comment]
:+1:

**Comment by Haud** [comment]
I'll merge; we can discuss the spacing in today's meeting and add it in a subsequent PR.

**Pull request merged**
