### PR TITLE
Added ruleset for implicit use of self

### PR DESCRIPTION
**Pull request by Haud**

### CODE REVIEW

**Comment by lk23lekkladf2** [comment]
The indentation in the examples seems to be wrong, but the content and rule looks good to me.
- [ ] Why is the indentation bigger?

**Comment by lk23lekkladf2** [comment]
@paulmiard

**Comment by haidalinda** [comment]
for further reference - Apple rejected a request to enforce use of `self`, so now the reasons why are clearly defined: http://ericasadun.com/2016/01/06/the-swift-evolution-proposal-se-0009-rejection/

**Comment by Haud** [comment]
@hkellaway Nice. Can you submit a PR here to add this to the rationale section of the `self` rule?

**Pull request merged**
